/**
 * TODO: wire to API — Replace mock data with calls to:
 * - matchesService.getUpcoming/getPast/getById
 * - invitesService.getByToken/getByUser
 * - matchmakingService.getSuggestions
 * - notificationsService.list
 * - playersService (for rankings, profile)
 */
import type {
  Player,
  Availability,
  Invite,
  Match,
  SuggestedOpponent,
  Notification,
  PlayerStats,
} from "./types"

export const CURRENT_USER_ID = "user-001"
export const CURRENT_PLAYER_ID = "player-001"

export const mockPlayers: Player[] = [
  {
    id: "player-001",
    userId: "user-001",
    name: "Alex Rivera",
    city: "Barcelona",
    latitude: 41.3851,
    longitude: 2.1734,
    levelValue: 5.2,
    levelConfidence: 0.85,
    rating: 1520,
    matchesPlayed: 47,
    wins: 28,
    losses: 19,
  },
  {
    id: "player-002",
    userId: "user-002",
    name: "Maria Santos",
    city: "Barcelona",
    latitude: 41.3921,
    longitude: 2.1648,
    levelValue: 5.0,
    levelConfidence: 0.78,
    rating: 1485,
    matchesPlayed: 35,
    wins: 20,
    losses: 15,
  },
  {
    id: "player-003",
    userId: "user-003",
    name: "Carlos Mendez",
    city: "Barcelona",
    latitude: 41.4036,
    longitude: 2.1744,
    levelValue: 5.5,
    levelConfidence: 0.92,
    rating: 1580,
    matchesPlayed: 62,
    wins: 41,
    losses: 21,
  },
  {
    id: "player-004",
    userId: "user-004",
    name: "Laura Chen",
    city: "Barcelona",
    latitude: 41.3780,
    longitude: 2.1900,
    levelValue: 4.8,
    levelConfidence: 0.70,
    rating: 1430,
    matchesPlayed: 22,
    wins: 11,
    losses: 11,
  },
  {
    id: "player-005",
    userId: "user-005",
    name: "Daniel Kim",
    city: "Barcelona",
    latitude: 41.3965,
    longitude: 2.1550,
    levelValue: 5.3,
    levelConfidence: 0.88,
    rating: 1545,
    matchesPlayed: 53,
    wins: 30,
    losses: 23,
  },
  {
    id: "player-006",
    userId: "user-006",
    name: "Sofia Petrov",
    city: "Barcelona",
    latitude: 41.3700,
    longitude: 2.1500,
    levelValue: 3.5,
    levelConfidence: 0.65,
    rating: 1380,
    matchesPlayed: 15,
    wins: 7,
    losses: 8,
  },
]

export const mockAvailabilities: Availability[] = [
  {
    id: "avail-001",
    userId: "user-001",
    playerId: "player-001",
    date: "2026-02-19",
    time: "18:00",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    levelRangeMin: 3.5,
    levelRangeMax: 5.0,
    surfacePreference: "clay",
    createdAt: "2026-02-17T10:00:00Z",
  },
  {
    id: "avail-002",
    userId: "user-001",
    playerId: "player-001",
    date: "2026-02-21",
    time: "10:00",
    location: "Pista Municipal Sarria",
    matchType: "practice",
    levelRangeMin: 3.0,
    levelRangeMax: 5.0,
    surfacePreference: "hard",
    createdAt: "2026-02-17T10:05:00Z",
  },
]

export const mockSuggestions: SuggestedOpponent[] = [
  {
    player: mockPlayers[1],
    distance: 1.2,
    levelDifference: 0.2,
    availabilityOverlap: ["Tuesday 18:00", "Thursday 18:00"],
    reason: "Friend connection • Very similar level (Δ 0.2) • 1.2 km away",
  },
  {
    player: mockPlayers[4],
    distance: 2.5,
    levelDifference: 0.1,
    availabilityOverlap: ["Saturday 10:00"],
    reason: "Previous opponent • Almost identical level (Δ 0.1) • Active recently • Strong reliability",
  },
  {
    player: mockPlayers[2],
    distance: 3.2,
    levelDifference: 0.3,
    availabilityOverlap: ["Wednesday 19:00"],
    reason: "Good level compatibility (Δ 0.3) • Close to your location • Recently active",
  },
]

export const mockInvites: Invite[] = [
  {
    id: "invite-001",
    token: "tok-abc123",
    fromUserId: "user-002",
    fromPlayerName: "Maria Santos",
    toUserId: "user-001",
    matchType: "competitive",
    date: "2026-02-20",
    time: "18:00",
    location: "Club Tennis Barcelona",
    status: "pending",
    isOpen: false,
    createdAt: "2026-02-16T14:00:00Z",
  },
  {
    id: "invite-002",
    token: "tok-def456",
    fromUserId: "user-003",
    fromPlayerName: "Carlos Mendez",
    matchType: "practice",
    date: "2026-02-22",
    time: "11:00",
    location: "Pista Municipal Sarria",
    status: "pending",
    isOpen: true,
    createdAt: "2026-02-16T16:00:00Z",
  },
  {
    id: "invite-003",
    token: "tok-ghi789",
    fromUserId: "user-005",
    fromPlayerName: "Daniel Kim",
    matchType: "competitive",
    date: "2026-02-23",
    time: "09:00",
    location: "Real Club de Tennis",
    status: "pending",
    isOpen: true,
    createdAt: "2026-02-17T08:00:00Z",
  },
  {
    id: "invite-004",
    token: "tok-jkl012",
    fromUserId: "user-001",
    fromPlayerName: "Alex Rivera",
    toUserId: "user-004",
    matchType: "practice",
    date: "2026-02-24",
    time: "16:00",
    location: "Pista Municipal Sarria",
    status: "pending",
    isOpen: false,
    createdAt: "2026-02-17T12:00:00Z",
  },
]

export const mockMatches: Match[] = [
  {
    id: "match-today-001",
    player1: mockPlayers[0],
    player2: mockPlayers[1],
    date: "2026-02-20",
    time: "18:00",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    status: "scheduled",
  },
  {
    id: "match-today-002",
    player1: mockPlayers[0],
    player2: mockPlayers[4],
    date: "2026-02-20",
    time: "14:30",
    location: "Pista Municipal Sarria",
    matchType: "practice",
    status: "scheduled",
  },
  {
    id: "match-001",
    player1: mockPlayers[0],
    player2: mockPlayers[1],
    date: "2026-02-19",
    time: "18:00",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    status: "scheduled",
  },
  {
    id: "match-002",
    player1: mockPlayers[0],
    player2: mockPlayers[4],
    date: "2026-02-21",
    time: "10:00",
    location: "Pista Municipal Sarria",
    matchType: "practice",
    status: "scheduled",
  },
  {
    id: "match-003",
    player1: mockPlayers[0],
    player2: mockPlayers[2],
    date: "2026-02-10",
    time: "17:00",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    status: "completed",
    result: {
      id: "result-001",
      matchId: "match-003",
      winnerId: "player-001",
      sets: [
        { setNumber: 1, player1Score: 6, player2Score: 4 },
        { setNumber: 2, player1Score: 7, player2Score: 5 },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: true,
      status: "confirmed",
      player1RatingChange: 15,
      player2RatingChange: -15,
    },
  },
  {
    id: "match-004",
    player1: mockPlayers[0],
    player2: mockPlayers[3],
    date: "2026-02-07",
    time: "11:00",
    location: "Pista Municipal Sarria",
    matchType: "practice",
    status: "completed",
    result: {
      id: "result-002",
      matchId: "match-004",
      winnerId: "player-004",
      sets: [
        { setNumber: 1, player1Score: 4, player2Score: 6 },
        { setNumber: 2, player1Score: 6, player2Score: 3 },
        { setNumber: 3, player1Score: 3, player2Score: 6 },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: true,
      status: "confirmed",
    },
  },
  {
    id: "match-005",
    player1: mockPlayers[0],
    player2: mockPlayers[1],
    date: "2026-02-14",
    time: "18:00",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    status: "awaiting_confirmation",
    result: {
      id: "result-003",
      matchId: "match-005",
      winnerId: "player-001",
      sets: [
        { setNumber: 1, player1Score: 6, player2Score: 2 },
        { setNumber: 2, player1Score: 6, player2Score: 4 },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: false,
      status: "pending",
      player1RatingChange: 12,
      player2RatingChange: -12,
    },
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    userId: "user-001",
    type: "invite_received",
    title: "New Match Invite",
    message: "Maria Santos invited you for a competitive match on Feb 20 at 18:00",
    read: false,
    createdAt: "2026-02-16T14:00:00Z",
    metadata: { inviteToken: "tok-abc123" },
  },
  {
    id: "notif-002",
    userId: "user-001",
    type: "result_pending",
    title: "Confirm Match Result",
    message: "Your match result against Maria Santos is awaiting confirmation",
    read: false,
    createdAt: "2026-02-14T20:00:00Z",
    metadata: { matchId: "match-005" },
  },
  {
    id: "notif-003",
    userId: "user-001",
    type: "rating_change",
    title: "Level Updated",
    message: "Your level improved after beating Carlos Mendez",
    read: true,
    createdAt: "2026-02-10T19:00:00Z",
  },
  {
    id: "notif-004",
    userId: "user-001",
    type: "match_completed",
    title: "Match Completed",
    message: "Your match against Carlos Mendez has been confirmed and completed",
    read: true,
    createdAt: "2026-02-10T18:30:00Z",
  },
]

export const mockPlayerStats: PlayerStats = {
  totalMatches: 47,
  competitiveMatches: 32,
  practiceMatches: 15,
  wins: 28,
  losses: 19,
  winRate: 59.6,
  averageOpponentLevel: 5.1,
  currentStreak: 2,
  streakType: "win",
  ratingHistory: [
    { date: "2025-12-22", rating: 4.5 },
    { date: "2025-12-29", rating: 4.6 },
    { date: "2026-01-05", rating: 4.6 },
    { date: "2026-01-12", rating: 4.8 },
    { date: "2026-01-19", rating: 4.7 },
    { date: "2026-01-26", rating: 4.9 },
    { date: "2026-02-02", rating: 5.0 },
    { date: "2026-02-09", rating: 5.2 },
    { date: "2026-02-16", rating: 5.2 },
  ],
}

// Additional completed matches for richer match history
export const mockExtendedMatches: Match[] = [
  ...mockMatches,
  {
    id: "match-006",
    player1: mockPlayers[0],
    player2: mockPlayers[2],
    date: "2026-01-28",
    time: "17:30",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    status: "completed",
    result: {
      id: "result-004",
      matchId: "match-006",
      winnerId: "player-003",
      sets: [
        { setNumber: 1, player1Score: 4, player2Score: 6 },
        { setNumber: 2, player1Score: 6, player2Score: 7 },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: true,
      status: "confirmed",
      player1RatingChange: -10,
      player2RatingChange: 10,
    },
  },
  {
    id: "match-007",
    player1: mockPlayers[0],
    player2: mockPlayers[1],
    date: "2026-01-21",
    time: "18:00",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    status: "completed",
    result: {
      id: "result-005",
      matchId: "match-007",
      winnerId: "player-001",
      sets: [
        { setNumber: 1, player1Score: 6, player2Score: 3 },
        { setNumber: 2, player1Score: 7, player2Score: 6, tiebreak: true },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: true,
      status: "confirmed",
      player1RatingChange: 12,
      player2RatingChange: -12,
    },
  },
  {
    id: "match-008",
    player1: mockPlayers[0],
    player2: mockPlayers[4],
    date: "2026-01-15",
    time: "10:30",
    location: "Pista Municipal Sarria",
    matchType: "practice",
    status: "completed",
    result: {
      id: "result-006",
      matchId: "match-008",
      winnerId: "player-001",
      sets: [
        { setNumber: 1, player1Score: 6, player2Score: 4 },
        { setNumber: 2, player1Score: 6, player2Score: 2 },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: true,
      status: "confirmed",
    },
  },
  {
    id: "match-009",
    player1: mockPlayers[0],
    player2: mockPlayers[2],
    date: "2026-01-08",
    time: "17:00",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    status: "completed",
    result: {
      id: "result-007",
      matchId: "match-009",
      winnerId: "player-001",
      sets: [
        { setNumber: 1, player1Score: 7, player2Score: 5 },
        { setNumber: 2, player1Score: 4, player2Score: 6 },
        { setNumber: 3, player1Score: 6, player2Score: 3 },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: true,
      status: "confirmed",
      player1RatingChange: 18,
      player2RatingChange: -18,
    },
  },
  {
    id: "match-010",
    player1: mockPlayers[0],
    player2: mockPlayers[3],
    date: "2025-12-30",
    time: "11:00",
    location: "Pista Municipal Sarria",
    matchType: "practice",
    status: "completed",
    result: {
      id: "result-008",
      matchId: "match-010",
      winnerId: "player-001",
      sets: [
        { setNumber: 1, player1Score: 6, player2Score: 1 },
        { setNumber: 2, player1Score: 6, player2Score: 3 },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: true,
      status: "confirmed",
    },
  },
  {
    id: "match-011",
    player1: mockPlayers[0],
    player2: mockPlayers[1],
    date: "2025-12-22",
    time: "18:00",
    location: "Club Tennis Barcelona",
    matchType: "competitive",
    status: "completed",
    result: {
      id: "result-009",
      matchId: "match-011",
      winnerId: "player-002",
      sets: [
        { setNumber: 1, player1Score: 5, player2Score: 7 },
        { setNumber: 2, player1Score: 6, player2Score: 4 },
        { setNumber: 3, player1Score: 4, player2Score: 6 },
      ],
      confirmedByPlayer1: true,
      confirmedByPlayer2: true,
      status: "confirmed",
      player1RatingChange: -14,
      player2RatingChange: 14,
    },
  },
]

// Recurring rivals computed from extended match data
export interface RivalData {
  player: Player
  matchesPlayed: number
  wins: number
  losses: number
  lastPlayed: string
  lastResult: "win" | "loss"
}

export const mockRivals: RivalData[] = [
  {
    player: mockPlayers[1],
    matchesPlayed: 4,
    wins: 2,
    losses: 2,
    lastPlayed: "2026-02-14",
    lastResult: "win",
  },
  {
    player: mockPlayers[2],
    matchesPlayed: 3,
    wins: 2,
    losses: 1,
    lastPlayed: "2026-02-10",
    lastResult: "win",
  },
  {
    player: mockPlayers[3],
    matchesPlayed: 2,
    wins: 1,
    losses: 1,
    lastPlayed: "2026-02-07",
    lastResult: "loss",
  },
]

// Performance insights
export const mockPerformanceInsights = [
  {
    id: "insight-01",
    icon: "surface",
    text: "You win more on clay",
    detail: "Your win rate on clay is 71%, compared to 48% on hard courts.",
  },
  {
    id: "insight-02",
    icon: "level",
    text: "You struggle against players above level 5.5",
    detail: "You have a 33% win rate against 5.5+ opponents. Focus on consistency in rallies.",
  },
  {
    id: "insight-03",
    icon: "close",
    text: "Your matches on hard are usually close",
    detail: "60% of your hard court matches go to 3 sets. You can close faster with aggressive serving.",
  },
  {
    id: "insight-04",
    icon: "time",
    text: "You perform better in evening matches",
    detail: "Your evening win rate is 68% vs 45% in morning matches. Consider scheduling accordingly.",
  },
  {
    id: "insight-05",
    icon: "streak",
    text: "You're on a 2-match winning streak",
    detail: "Momentum matters. Your best streak this quarter was 4 consecutive wins in January.",
  },
]

// Personal progress metrics
export const mockPersonalProgress = {
  matchesThisMonth: 5,
  winRateOverall: 59.6,
  winRateMonthly: 60,
  currentLevel: 5.2,
  levelEvolution: [4.5, 4.6, 4.6, 4.8, 4.7, 4.9, 5.0, 5.2],
  levelEvolutionWeeks: ["W-8", "W-7", "W-6", "W-5", "W-4", "W-3", "W-2", "W-1"],
  mostPlayedSurface: "Clay",
  mostFrequentRival: "Maria Santos",
}
